#include <cstdlib>
#include "../algostuff.hpp"
using namespace std;
/*
• generate_n() assigns the values that are generated by a call of op()
  to the first num elements in the range starting with beg. If num is negative, 
  generate_n() does nothing (specified only since C++11)
*/
int main()
{
	list<int> coll;
	// insert five random numbers
	generate_n(back_inserter(coll), // beginning of destination range
		5, // count
		rand); // new value generator
	PRINT_ELEMENTS(coll);
	// overwrite with five new random numbers
	generate(coll.begin(), coll.end(), // destination range
		rand); // new value generator
	PRINT_ELEMENTS(coll);
}